services:
  test:
    extends:
      file: docker-compose-base.yml
      service: base
    entrypoint: /code/.venv/bin/python
    user: "0:0"
    command: manage.py test -v2
    env_file:
        - conf/test.env
  sut:
    image: ubuntu
    command: "true"
